version: "3.1"
services:
    db:
        container_name: odoo-db
        image: postgres:16
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - odoo-db-data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        tty: true

    odoo:
        container_name: odoo-web
        build: .
        depends_on:
            - db
        ports:
            - "8069:8069"
            - "8888:8888"
        volumes:
            - odoo-web-data:/var/lib/odoo
            - ./config:/etc/odoo
            - ./addons:/mnt/extra-addons
        environment:
            - HOST=db
            - PORT=5432
            - USER=odoo
            - PASSWORD=odoo
            - PYTHONUNBUFFERED=1
            - PIP_AUTO_INSTALL=1
            - DEBUGPY_ENABLE=1
            - PUID = 1000
            - PGID = 1000
        command: /usr/bin/python3 -m debugpy --listen 0.0.0.0:8888 /usr/bin/odoo -c /etc/odoo/odoo.conf
        tty: true

volumes:
    odoo-web-data:
    odoo-db-data:
networks:
    default:
        name: odoo-network
